# Generated by Django 4.2.6 on 2023-10-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="election",
            old_name="end_time",
            new_name="End_time",
        ),
        migrations.RenameField(
            model_name="election",
            old_name="is_active",
            new_name="Is_active",
        ),
        migrations.RenameField(
            model_name="election",
            old_name="start_time",
            new_name="Start_time",
        ),
        migrations.RenameField(
            model_name="election",
            old_name="title",
            new_name="Title",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="candidate",
            new_name="Candidate",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="election",
            new_name="Election",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="vote_count",
            new_name="Vote_count",
        ),
        migrations.RenameField(
            model_name="votedornot",
            old_name="has_voted",
            new_name="Has_voted",
        ),
        migrations.RenameField(
            model_name="votedornot",
            old_name="user",
            new_name="User",
        ),
        migrations.AlterField(
            model_name="user",
            name="PhoneNumber",
            field=models.IntegerField(max_length=15),
        ),
    ]
