# Generated by Django 4.2.6 on 2023-10-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_rename_end_time_election_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="PhoneNumber",
            field=models.IntegerField(),
        ),
    ]
