# Generated by Django 4.2.6 on 2023-10-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_alter_user_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="PhoneNumber",
            field=models.CharField(max_length=15),
        ),
    ]
