# Generated by Django 4.2.6 on 2023-10-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0004_alter_user_phonenumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="Email",
        ),
    ]
