# Generated by Django 4.2.6 on 2023-10-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0005_remove_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="PhoneNumber",
        ),
    ]
