# Generated by Django 4.2.6 on 2023-10-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0006_remove_user_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="Vote_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
